controller_manager:
  ros__parameters:
    update_rate: 200  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


mecanum_drive_controller:
  ros__parameters:
    front_left_wheel_command_joint_name: front_left_wheel_joint
    front_right_wheel_command_joint_name: front_right_wheel_joint
    rear_left_wheel_command_joint_name: rear_left_wheel_joint
    rear_right_wheel_command_joint_name: rear_right_wheel_joint
    reference_topic: "/mecanum_drive_controller/reference"
    use_stamped_vel: true 
    base_frame_id: "base_link"
    wheel_separation_x: 0.4318 
    wheel_separation_y: 0.635
    wheel_radius: 0.2032  
    kinematics:
      wheels_radius:  0.2032


arm_controller:
  ros__parameters:     
      joints:
        - Joint_1
        - Joint_2
        - Joint_3
        - Joint_4
        - Joint_5
        - End_effector_Joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      action_monitor_rate: 20.0
      allow_partial_joints_goal: true

gripper_controller:
  ros__parameters: 
      joints:
        - Gripper_arm_left_Joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      action_monitor_rate: 20.0
      allow_partial_joints_goal: true
