controller_manager:
  ros__parameters:
    update_rate: 200  # Hz, suitable for real-time control
    use_sim_time: true  # Required for Gazebo simulation

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

mecanum_drive_controller:
  ros__parameters:
    front_left_wheel_command_joint_name: front_left_wheel_joint
    front_right_wheel_command_joint_name: front_right_wheel_joint
    rear_left_wheel_command_joint_name: rear_left_wheel_joint
    rear_right_wheel_command_joint_name: rear_right_wheel_joint
    reference_topic: "/mecanum_drive_controller/reference"
    use_stamped_vel: true 
    base_frame_id: "base_link"
    wheel_separation_x: 0.4318 
    wheel_separation_y: 0.635
    wheel_radius: 0.2032  
    kinematics:
      wheels_radius:  0.2032
    command_timeout: 0.5  # Resets to zero velocity if no command within 0.5s